name: 1.0.0$(Rev:.r)

trigger:
  paths:
    include:
    - webapp/*
    - data/*
    - azure-pipeline-webapp.yml

variables:
  AzureSubscription: 10M Client Demo
  RGName: cd-mlops
  Location: westus2
  WebAppNamePrefix: cd-diabetes
  SKU: B1
  WorkspaceName: cdmlops
  CreatedBy: colin

stages:
- stage: build
  displayName: Build website
  jobs:
  - job: build
    displayName: Compile and Package
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self

      - task: DotNetCoreCLI@2
        displayName: dotnet build
        inputs:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration Release /p:Version=$(Build.BuildNumber)'
      
      - task: DotNetCoreCLI@2
        displayName: dotnet publish
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration Release --output $(Pipeline.Workspace)/site /p:Version=$(Build.BuildNumber)'
          zipAfterPublish: True
      
      - task: PublishPipelineArtifact@1
        displayName: Publish Artifact
        inputs:
          targetPath: $(Pipeline.Workspace)/site
          ArtifactName: site

- stage: dev
  displayName: Dev
  dependsOn: build
  jobs:
  - template: templates/job-deploy-webapp.yml
    parameters:
      Environment: 'MLOps-Dev'
      EnvironmentName: DEV
      ServiceName: 'diabetes-aci'
      WorkspaceName: $(WorkspaceName)
      AzureSubscription: $(AzureSubscription)
      CreatedBy: $(CreatedBy)
      Location: $(Location)
      RGName: $(RGName)
      SKU: $(SKU)
      WebAppNamePrefix: $(WebAppNamePrefix)
          
- stage: prod
  displayName: Prod
  dependsOn: dev
  jobs:
  - template: templates/job-deploy-webapp.yml
    parameters:
      Environment: 'MLOps-PROD'
      EnvironmentName: PROD
      ServiceName: 'diabetes-aks'
      WorkspaceName: $(WorkspaceName)
      AzureSubscription: $(AzureSubscription)
      CreatedBy: $(CreatedBy)
      Location: $(Location)
      RGName: $(RGName)
      SKU: $(SKU)
      WebAppNamePrefix: $(WebAppNamePrefix)
    