# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: scoring_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.8

- pip:
  - azureml-defaults
  - inference-schema[numpy-support]
  - inference-schema[pandas-support]
- scikit-learn=0.21.2
- joblib=0.13.2
- numpy=1.16.4
- pandas=0.24.2
- matplotlib=3.0.2
- seaborn=0.9.0
- azureml-automl-core=1.0.81
- azureml-train-automl=1.0.81
