patameters:
  AzureSubscription: 10M Client Demo
  RGName: cd-mlops
  Location: westus2
  WorkspaceName: cdmlops
  ContainerName: diabetesdata
  DataFileName: diabetes_pima.csv
  TrainingScript: train_pima_model.py
  PublishPath: ''
  TrainSteps: []

#   ModelName: diabetesmodel
#   ServiceName: diabetes-aci
#   ProdServiceName: diabetes-aks
#   AKSCluster: cd-mlcluster
#   AKSNodeSize: Standard_B4ms
#   AKSNodeCount: 2
#   CreatedBy: colin

jobs:
- deployment: trainModel
  displayName: Train Model
  pool:
    vmImage: ubuntu-latest
  container: mlops
  environment:
    Workspace
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self   # get config files in repo

        - task: AzureCLI@2
          displayName: Upload training data
          inputs:
            azureSubscription: $(AzureSubscription)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              echo "Uploading training data"
              dataStoreName=$(az ml datastore show-default -w $WORKSPACE -g $RG --query name -o tsv)
              az ml datastore upload -w $WORKSPACE -g $RG -n $dataStoreName -p data -u $CONTAINER --overwrite true
              
              # create a variable with the datastoreName for subsequent tasks
              echo "##vso[task.setvariable variable=DataStoreName;]$dataStoreName"
          env:
            RG: $(RGName)
            LOCATION: $(Location)
            WORKSPACE: $(WorkspaceName)
            CONTAINER: $(ContainerName)
        
        - ${{ for step in trainSteps }}:
          - task: ${{ step}} 
          
        - task: PublishPipelineArtifact@1
          displayName: Publish Artifact
          inputs:
            targetPath: ${{ parameters.PublishPath }} # $(Pipeline.Workspace)/training
            ArtifactName: model